import { useCallback, useSyncExternalStore } from "react";

export const LANGUAGE_OPTIONS = [
  { code: "bg", label: "Български" },
  { code: "en", label: "English" },
  { code: "de", label: "Deutsch" },
];

const LANGUAGE_STORAGE_KEY = "eksait-language";
const DEFAULT_LANGUAGE = "bg";
const languageCodes = new Set(LANGUAGE_OPTIONS.map((language) => language.code));
const languageListeners = new Set();

const TRANSLATIONS = {
  bg: {
    "category.darjachi": "Държачи",
    "category.frezi": "Фрези",
    "category.izmervatelni": "Измервателни",
    "category.kalibri": "Калибри",
    "category.kobalt": "Кобалт",
    "category.metchici": "Метчици",
    "category.nojove": "Ножове",
    "category.plashki": "Плашки",
    "category.plastini": "Пластини",
    "category.shtangi": "Щанги",
    "category.sverdla": "Свредла",
    "common.add": "Добави",
    "common.adding": "Добавяне...",
    "common.all": "Всички",
    "common.allProducts": "Всички продукти",
    "common.viewAllProducts": "Виж всички",
    "common.cart": "Количка",
    "common.categories": "Категории",
    "common.choose": "Избери",
    "common.clear": "Изчисти",
    "common.clearFilters": "Изчисти филтрите",
    "common.close": "Затвори",
    "common.contacts": "Контакти",
    "common.filters": "Филтри",
    "common.filtersAndCategories": "Филтри и категории",
    "common.loading": "Зареждане...",
    "common.noImage": "Няма снимка",
    "common.noResults": "Няма резултати.",
    "common.noVariants": "Няма варианти",
    "common.product": "Продукт",
    "common.profile": "Профил",
    "common.search": "Търсене",
    "common.searching": "Търсене...",
    "common.sort": "Сортиране",
    "common.view": "Преглед",
    "common.viewDetailsPrompt": "Натисни преглед за още подробности",
    "cart.checkout": "Към поръчката",
    "cart.checkoutLead": "Прегледайте избраните продукти, въведете данни за доставка и завършете поръчката.",
    "cart.closeCart": "Затвори количката",
    "cart.continue": "Продължи пазаруването",
    "cart.empty": "Количката е празна.",
    "cart.total": "Общо",
    "cart.yourOrder": "Вашата поръчка",
    "equipment.emptyBody": "Когато добавите оборудване през backend-а, то ще се появи автоматично тук.",
    "equipment.emptyTitle": "Няма добавено оборудване.",
    "equipment.filtersAria": "Филтри за оборудване",
    "equipment.refine": "Уточни оборудването",
    "equipment.searchPlaceholder": "Търси оборудване",
    "equipment.title": "Оборудване",
    "footer.brand": "Ексайт Къмпани ООД",
    "footer.brandAria": "Excite Company начало",
    "footer.brandText": "Голяма част от предлаганите изделия се поддържат в наличност, и при необходимост от спешна доставка можем да реагираме своевременно. Това ни дава възможност да бъдем гъвкави и да обслужваме нашите клиенти, като удовлетворяваме и техните специфични производствени нужди. Стремим се да постигнем оптимално съотношение между качество и цена.",
    "footer.client": "За клиента",
    "footer.copyright": "© {year} Ексайт Къмпани ООД. Всички права запазени.",
    "footer.location": "гр. Стара Загора, България",
    "footer.myProfile": "Моят профил",
    "footer.nav": "Навигация",
    "footer.order": "Поръчка",
    "footer.phone": "Тел",
    "footer.terms": "Общи условия",
    "footer.workHours": "Пон. - Пет.: 09:00 - 17:30",
    "header.brandAria": "Excite Company начало",
    "header.cartWithCount": "Количка с {count} продукта",
    "header.changeLanguageTo": "Смени езика на {language}",
    "header.hello": "Здравей, {name}!",
    "header.logout": "Изход",
    "header.menu": "Меню",
    "header.orders": "Моите поръчки",
    "header.profileOf": "Профил на {name}",
    "header.searchProducts": "Търси продукти",
    "header.switchLanguage": "Смяна на езика",
    "home.emptyCategory": "Няма налични продукти в тази категория.",
    "home.loadingProducts": "Зареждане на продукти...",
    "home.more": "Още",
    "home.nextCategory": "Следващи {category}",
    "home.prevCategory": "Предишни {category}",
    "home.videoAria": "За Ексайт Къмпани",
    "nav.about": "За нас",
    "nav.contact": "Контакти",
    "nav.equipment": "Оборудване",
    "nav.home": "Начало",
    "nav.tools": "Инструменти",
    "pagination.next": "Напред",
    "pagination.pages": "Страници",
    "pagination.perPage": "На страница",
    "pagination.perPageAria": "Брой продукти на страница",
    "pagination.prev": "Назад",
    "price.max": "Максимална цена",
    "price.min": "Минимална цена",
    "price.title": "Цена",
    "product.addToCart": "Добави в количката",
    "product.addedToCart": "Продуктът беше добавен в количката.",
    "product.availability": "Наличност",
    "product.available": "В наличност",
    "product.code": "Код",
    "product.detailsAria": "Информация за продукта",
    "product.extraInfo": "Допълнителна информация",
    "product.imageOpen": "Отвори снимката",
    "product.imagePrevious": "Предишна снимка",
    "product.imageNext": "Следваща снимка",
    "product.imageShow": "Покажи снимка",
    "product.imageThumbs": "Снимки на продукта",
    "product.invalidQuantity": "Изберете валидно количество.",
    "product.noMatchingSizes": "Няма типове/размери, които съвпадат с търсенето.",
    "product.noPrice": "Няма цена",
    "product.noPriceMessage": "Този тип/размер няма въведена цена и не може да бъде поръчан. Изберете друг тип/размер.",
    "product.notAvailable": "Не е наличен",
    "product.notFound": "Продуктът не е намерен.",
    "product.outOfStock": "Изчерпан",
    "product.outOfStockLower": "изчерпан",
    "product.pageSizeHint": "По 10 на страница",
    "product.priceByVariant": "Цена според вариант",
    "product.quantity": "Количество",
    "product.quantityFor": "Количество за {name}",
    "product.related": "Свързани продукти",
    "product.relatedNav": "Навигация за свързани продукти",
    "product.relatedNext": "Следващи свързани продукти",
    "product.relatedPrevious": "Предишни свързани продукти",
    "product.searchSize": "Търси по тип/размер",
    "product.selectSize": "Изберете тип/размер",
    "product.selectSizeShort": "Избери тип/размер",
    "product.size": "Тип/Размер",
    "product.sizeTable": "Таблица с типове/размери",
    "product.tableAdd": "Добавяне",
    "product.tableQuantity": "Бройка",
    "product.tableQuantityFor": "Бройка за {name}",
    "product.tableShown": "Показани {from}-{to} от {total}",
    "product.unavailableMessage": "Продуктът не е наличен.",
    "product.variantAvailableLower": "в наличност",
    "product.variantNoPriceLower": "няма въведена цена",
    "product.mustSelectSize": "Изберете тип/размер преди добавяне в количката.",
    "product.tooMany": "Не може да закупите повече.",
    "search.emptyBody": "Опитайте с друго име или разгледайте всички продукти.",
    "search.emptyTitle": "Няма намерени резултати{query}.",
    "search.goProducts": "Към продуктите",
    "search.heading": "Търсене",
    "search.queryTitle": "Продукти с името \"{query}\"",
    "search.title": "Търсене на продукти",
    "search.subtitle": "Резултатите се търсят по име, категория, описание и код на продукта.",
    "sort.nameAsc": "По име А-Я",
    "sort.nameDesc": "По име Я-А",
    "sort.priceAsc": "Цена възходяща",
    "sort.priceDesc": "Цена низходяща",
    "tools.chooseCategory": "Избери категория",
    "tools.empty": "Няма намерени продукти в тази категория.",
    "tools.foundOne": "намерен продукт",
    "tools.foundMany": "намерени продукта",
    "tools.refine": "Уточни резултатите",
    "tools.searchPlaceholder": "Търси по име, описание или категория",
    "tools.title": "Инструменти",
  },
  en: {
    "category.darjachi": "Holders",
    "category.frezi": "Milling cutters",
    "category.izmervatelni": "Measuring tools",
    "category.kalibri": "Gauges",
    "category.kobalt": "Cobalt",
    "category.metchici": "Taps",
    "category.nojove": "Knives",
    "category.plashki": "Dies",
    "category.plastini": "Inserts",
    "category.shtangi": "Bars",
    "category.sverdla": "Drills",
    "common.add": "Add",
    "common.adding": "Adding...",
    "common.all": "All",
    "common.allProducts": "All products",
    "common.viewAllProducts": "View all",
    "common.cart": "Cart",
    "common.categories": "Categories",
    "common.choose": "Choose",
    "common.clear": "Clear",
    "common.clearFilters": "Clear filters",
    "common.close": "Close",
    "common.contacts": "Contacts",
    "common.filters": "Filters",
    "common.filtersAndCategories": "Filters and categories",
    "common.loading": "Loading...",
    "common.noImage": "No image",
    "common.noResults": "No results.",
    "common.noVariants": "No variants",
    "common.product": "Product",
    "common.profile": "Profile",
    "common.search": "Search",
    "common.searching": "Searching...",
    "common.sort": "Sort",
    "common.view": "View",
    "common.viewDetailsPrompt": "Open the product for more details",
    "cart.checkout": "Checkout",
    "cart.checkoutLead": "Review the selected products, enter delivery details, and complete the order.",
    "cart.closeCart": "Close cart",
    "cart.continue": "Continue shopping",
    "cart.empty": "The cart is empty.",
    "cart.total": "Total",
    "cart.yourOrder": "Your order",
    "equipment.emptyBody": "When equipment is added through the backend, it will appear here automatically.",
    "equipment.emptyTitle": "No equipment has been added.",
    "equipment.filtersAria": "Equipment filters",
    "equipment.refine": "Refine equipment",
    "equipment.searchPlaceholder": "Search equipment",
    "equipment.title": "Equipment",
    "footer.brand": "Excite Company Ltd.",
    "footer.brandAria": "Excite Company home",
    "footer.brandText": "A large part of the offered products is kept in stock, and when urgent delivery is needed we can react quickly. This allows us to stay flexible and serve our clients while meeting their specific production needs. We aim for the best balance between quality and price.",
    "footer.client": "Customer",
    "footer.copyright": "© {year} Excite Company Ltd. All rights reserved.",
    "footer.location": "Stara Zagora, Bulgaria",
    "footer.myProfile": "My profile",
    "footer.nav": "Navigation",
    "footer.order": "Order",
    "footer.phone": "Tel",
    "footer.terms": "Terms and conditions",
    "footer.workHours": "Mon. - Fri.: 09:00 - 17:30",
    "header.brandAria": "Excite Company home",
    "header.cartWithCount": "Cart with {count} products",
    "header.changeLanguageTo": "Change language to {language}",
    "header.hello": "Hello, {name}!",
    "header.logout": "Log out",
    "header.menu": "Menu",
    "header.orders": "My orders",
    "header.profileOf": "{name}'s profile",
    "header.searchProducts": "Search products",
    "header.switchLanguage": "Change language",
    "home.emptyCategory": "There are no available products in this category.",
    "home.loadingProducts": "Loading products...",
    "home.more": "More",
    "home.nextCategory": "Next {category}",
    "home.prevCategory": "Previous {category}",
    "home.videoAria": "About Excite Company",
    "nav.about": "About us",
    "nav.contact": "Contacts",
    "nav.equipment": "Equipment",
    "nav.home": "Home",
    "nav.tools": "Tools",
    "pagination.next": "Next",
    "pagination.pages": "Pages",
    "pagination.perPage": "Per page",
    "pagination.perPageAria": "Products per page",
    "pagination.prev": "Back",
    "price.max": "Maximum price",
    "price.min": "Minimum price",
    "price.title": "Price",
    "product.addToCart": "Add to cart",
    "product.addedToCart": "The product was added to the cart.",
    "product.availability": "Availability",
    "product.available": "In stock",
    "product.code": "Code",
    "product.detailsAria": "Product information",
    "product.extraInfo": "Additional information",
    "product.imageOpen": "Open image",
    "product.imagePrevious": "Previous image",
    "product.imageNext": "Next image",
    "product.imageShow": "Show image",
    "product.imageThumbs": "Product images",
    "product.invalidQuantity": "Choose a valid quantity.",
    "product.noMatchingSizes": "No types/sizes match your search.",
    "product.noPrice": "No price",
    "product.noPriceMessage": "This type/size has no price and cannot be ordered. Choose another type/size.",
    "product.notAvailable": "Not available",
    "product.notFound": "Product not found.",
    "product.outOfStock": "Out of stock",
    "product.outOfStockLower": "out of stock",
    "product.pageSizeHint": "10 per page",
    "product.priceByVariant": "Price by variant",
    "product.quantity": "Quantity",
    "product.quantityFor": "Quantity for {name}",
    "product.related": "Related products",
    "product.relatedNav": "Related products navigation",
    "product.relatedNext": "Next related products",
    "product.relatedPrevious": "Previous related products",
    "product.searchSize": "Search by type/size",
    "product.selectSize": "Choose type/size",
    "product.selectSizeShort": "Choose type/size",
    "product.size": "Type/Size",
    "product.sizeTable": "Type/size table",
    "product.tableAdd": "Add",
    "product.tableQuantity": "Qty",
    "product.tableQuantityFor": "Qty for {name}",
    "product.tableShown": "Showing {from}-{to} of {total}",
    "product.unavailableMessage": "The product is not available.",
    "product.variantAvailableLower": "in stock",
    "product.variantNoPriceLower": "no price entered",
    "product.mustSelectSize": "Choose a type/size before adding to the cart.",
    "product.tooMany": "You cannot purchase more.",
    "search.emptyBody": "Try another name or browse all products.",
    "search.emptyTitle": "No results found{query}.",
    "search.goProducts": "To products",
    "search.heading": "Search",
    "search.queryTitle": "Products named \"{query}\"",
    "search.title": "Product search",
    "search.subtitle": "Results are searched by name, category, description, and product code.",
    "sort.nameAsc": "Name A-Z",
    "sort.nameDesc": "Name Z-A",
    "sort.priceAsc": "Price ascending",
    "sort.priceDesc": "Price descending",
    "tools.chooseCategory": "Choose category",
    "tools.empty": "No products found in this category.",
    "tools.foundOne": "product found",
    "tools.foundMany": "products found",
    "tools.refine": "Refine results",
    "tools.searchPlaceholder": "Search by name, description, or category",
    "tools.title": "Tools",
  },
  de: {
    "category.darjachi": "Halter",
    "category.frezi": "Fräser",
    "category.izmervatelni": "Messwerkzeuge",
    "category.kalibri": "Lehren",
    "category.kobalt": "Kobalt",
    "category.metchici": "Gewindebohrer",
    "category.nojove": "Messer",
    "category.plashki": "Schneideisen",
    "category.plastini": "Wendeschneidplatten",
    "category.shtangi": "Stangen",
    "category.sverdla": "Bohrer",
    "common.add": "Hinzufügen",
    "common.adding": "Wird hinzugefügt...",
    "common.all": "Alle",
    "common.allProducts": "Alle Produkte",
    "common.viewAllProducts": "Alle anzeigen",
    "common.cart": "Warenkorb",
    "common.categories": "Kategorien",
    "common.choose": "Auswählen",
    "common.clear": "Zurücksetzen",
    "common.clearFilters": "Filter zurücksetzen",
    "common.close": "Schließen",
    "common.contacts": "Kontakt",
    "common.filters": "Filter",
    "common.filtersAndCategories": "Filter und Kategorien",
    "common.loading": "Laden...",
    "common.noImage": "Kein Bild",
    "common.noResults": "Keine Ergebnisse.",
    "common.noVariants": "Keine Varianten",
    "common.product": "Produkt",
    "common.profile": "Profil",
    "common.search": "Suche",
    "common.searching": "Suche...",
    "common.sort": "Sortierung",
    "common.view": "Ansehen",
    "common.viewDetailsPrompt": "Produkt für weitere Details öffnen",
    "cart.checkout": "Zur Bestellung",
    "cart.checkoutLead": "Prüfen Sie die ausgewählten Produkte, geben Sie die Lieferdaten ein und schließen Sie die Bestellung ab.",
    "cart.closeCart": "Warenkorb schließen",
    "cart.continue": "Weiter einkaufen",
    "cart.empty": "Der Warenkorb ist leer.",
    "cart.total": "Gesamt",
    "cart.yourOrder": "Ihre Bestellung",
    "equipment.emptyBody": "Wenn Maschinen über das Backend hinzugefügt werden, erscheinen sie automatisch hier.",
    "equipment.emptyTitle": "Es wurden keine Maschinen hinzugefügt.",
    "equipment.filtersAria": "Maschinenfilter",
    "equipment.refine": "Maschinen eingrenzen",
    "equipment.searchPlaceholder": "Maschinen suchen",
    "equipment.title": "Maschinen",
    "footer.brand": "Excite Company GmbH",
    "footer.brandAria": "Excite Company Startseite",
    "footer.brandText": "Ein großer Teil der angebotenen Produkte wird auf Lager gehalten, und bei dringender Lieferung können wir schnell reagieren. Dadurch bleiben wir flexibel und erfüllen die spezifischen Produktionsanforderungen unserer Kunden. Wir streben das optimale Verhältnis zwischen Qualität und Preis an.",
    "footer.client": "Kundenbereich",
    "footer.copyright": "© {year} Excite Company GmbH. Alle Rechte vorbehalten.",
    "footer.location": "Stara Zagora, Bulgarien",
    "footer.myProfile": "Mein Profil",
    "footer.nav": "Navigation",
    "footer.order": "Bestellung",
    "footer.phone": "Tel",
    "footer.terms": "Allgemeine Bedingungen",
    "footer.workHours": "Mo. - Fr.: 09:00 - 17:30",
    "header.brandAria": "Excite Company Startseite",
    "header.cartWithCount": "Warenkorb mit {count} Produkten",
    "header.changeLanguageTo": "Sprache auf {language} ändern",
    "header.hello": "Hallo, {name}!",
    "header.logout": "Abmelden",
    "header.menu": "Menü",
    "header.orders": "Meine Bestellungen",
    "header.profileOf": "Profil von {name}",
    "header.searchProducts": "Produkte suchen",
    "header.switchLanguage": "Sprache wechseln",
    "home.emptyCategory": "In dieser Kategorie sind keine Produkte verfügbar.",
    "home.loadingProducts": "Produkte werden geladen...",
    "home.more": "Mehr",
    "home.nextCategory": "Nächste {category}",
    "home.prevCategory": "Vorherige {category}",
    "home.videoAria": "Über Excite Company",
    "nav.about": "Über uns",
    "nav.contact": "Kontakt",
    "nav.equipment": "Maschinen",
    "nav.home": "Start",
    "nav.tools": "Werkzeuge",
    "pagination.next": "Weiter",
    "pagination.pages": "Seiten",
    "pagination.perPage": "Pro Seite",
    "pagination.perPageAria": "Produkte pro Seite",
    "pagination.prev": "Zurück",
    "price.max": "Maximaler Preis",
    "price.min": "Minimaler Preis",
    "price.title": "Preis",
    "product.addToCart": "In den Warenkorb",
    "product.addedToCart": "Das Produkt wurde in den Warenkorb gelegt.",
    "product.availability": "Verfügbarkeit",
    "product.available": "Auf Lager",
    "product.code": "Code",
    "product.detailsAria": "Produktinformation",
    "product.extraInfo": "Zusätzliche Informationen",
    "product.imageOpen": "Bild öffnen",
    "product.imagePrevious": "Vorheriges Bild",
    "product.imageNext": "Nächstes Bild",
    "product.imageShow": "Bild anzeigen",
    "product.imageThumbs": "Produktbilder",
    "product.invalidQuantity": "Wählen Sie eine gültige Menge.",
    "product.noMatchingSizes": "Keine Typen/Größen entsprechen der Suche.",
    "product.noPrice": "Kein Preis",
    "product.noPriceMessage": "Für diesen Typ/diese Größe ist kein Preis hinterlegt und er kann nicht bestellt werden. Wählen Sie einen anderen Typ/eine andere Größe.",
    "product.notAvailable": "Nicht verfügbar",
    "product.notFound": "Produkt nicht gefunden.",
    "product.outOfStock": "Ausverkauft",
    "product.outOfStockLower": "ausverkauft",
    "product.pageSizeHint": "10 pro Seite",
    "product.priceByVariant": "Preis nach Variante",
    "product.quantity": "Menge",
    "product.quantityFor": "Menge für {name}",
    "product.related": "Ähnliche Produkte",
    "product.relatedNav": "Navigation für ähnliche Produkte",
    "product.relatedNext": "Nächste ähnliche Produkte",
    "product.relatedPrevious": "Vorherige ähnliche Produkte",
    "product.searchSize": "Nach Typ/Größe suchen",
    "product.selectSize": "Typ/Größe auswählen",
    "product.selectSizeShort": "Typ/Größe wählen",
    "product.size": "Typ/Größe",
    "product.sizeTable": "Typ-/Größentabelle",
    "product.tableAdd": "Hinzufügen",
    "product.tableQuantity": "Menge",
    "product.tableQuantityFor": "Menge für {name}",
    "product.tableShown": "Angezeigt {from}-{to} von {total}",
    "product.unavailableMessage": "Das Produkt ist nicht verfügbar.",
    "product.variantAvailableLower": "auf Lager",
    "product.variantNoPriceLower": "kein Preis hinterlegt",
    "product.mustSelectSize": "Wählen Sie einen Typ/eine Größe, bevor Sie den Artikel in den Warenkorb legen.",
    "product.tooMany": "Sie können nicht mehr kaufen.",
    "search.emptyBody": "Versuchen Sie einen anderen Namen oder sehen Sie sich alle Produkte an.",
    "search.emptyTitle": "Keine Ergebnisse gefunden{query}.",
    "search.goProducts": "Zu den Produkten",
    "search.heading": "Suche",
    "search.queryTitle": "Produkte mit dem Namen \"{query}\"",
    "search.title": "Produktsuche",
    "search.subtitle": "Die Ergebnisse werden nach Name, Kategorie, Beschreibung und Produktcode durchsucht.",
    "sort.nameAsc": "Name A-Z",
    "sort.nameDesc": "Name Z-A",
    "sort.priceAsc": "Preis aufsteigend",
    "sort.priceDesc": "Preis absteigend",
    "tools.chooseCategory": "Kategorie auswählen",
    "tools.empty": "Keine Produkte in dieser Kategorie gefunden.",
    "tools.foundOne": "Produkt gefunden",
    "tools.foundMany": "Produkte gefunden",
    "tools.refine": "Ergebnisse eingrenzen",
    "tools.searchPlaceholder": "Nach Name, Beschreibung oder Kategorie suchen",
    "tools.title": "Werkzeuge",
  },
};

const EXTRA_TRANSLATIONS = {
  bg: {
    "auth.accountExists": "Вече имате профил?",
    "auth.createAccount": "Създайте регистрация",
    "auth.createProfile": "Създаване на профил",
    "auth.email": "Имейл",
    "auth.forgotKicker": "Профил",
    "auth.forgotLead": "Въведете имейла към профила си и ще получите линк за задаване на нова парола.",
    "auth.forgotPassword": "Забравена парола",
    "auth.forgotQuestion": "Забравена парола?",
    "auth.login": "Вписване",
    "auth.loginFormTitle": "Вход в профила",
    "auth.loginLead": "Влезте в профила си, за да преглеждате поръчки, данни за доставка и клиентски настройки.",
    "auth.loginRetry": "Опитай отново след {seconds} сек.",
    "auth.loginRetryFormal": "Опитайте отново след {seconds} сек.",
    "auth.name": "Име",
    "auth.newAccount": "Нов профил",
    "auth.newPassword": "Нова парола",
    "auth.newPasswordLead": "Задайте нова парола за профила си. Линкът е еднократен и трябва да се използва преди да изтече.",
    "auth.noAccount": "Нямате профил?",
    "auth.password": "Парола",
    "auth.passwordConfirm": "Повторете паролата",
    "auth.passwordConfirmNew": "Повторете новата парола",
    "auth.passwordNew": "Нова парола",
    "auth.profile": "Профил",
    "auth.recoverAccess": "Възстановяване на достъп",
    "auth.register": "Регистрация",
    "auth.registering": "Регистрация...",
    "auth.registerLead": "Създайте клиентски профил, за да поръчвате по-бързо и да пазите основните си данни за бъдещи заявки.",
    "auth.rememberMe": "Запомни ме",
    "auth.resetPassword": "Смяна на парола",
    "auth.saveNewPassword": "Запази новата парола",
    "auth.saving": "Запазване...",
    "auth.sendLink": "Изпрати линк",
    "auth.sending": "Изпращане...",
    "auth.waitSeconds": "Изчакайте {seconds} сек.",
    "auth.backToLogin": "Към вписване",
    "auth.rememberedPassword": "Спомнихте си паролата?",
    "auth.accessRestored": "Вече имате достъп?",
    "auth.showPassword": "Покажи паролата",
    "auth.hidePassword": "Скрий паролата",
    "cart.address": "Адрес за доставка",
    "cart.apm": "Еконтомат",
    "cart.backToCart": "Обратно към количката",
    "cart.bankTransfer": "Банков превод",
    "cart.cardPayment": "Плащане с карта",
    "cart.cardPaymentUnavailable": "Плащането с карта временно не е налично.",
    "cart.city": "Град",
    "cart.cityEnglishHint": "Въведете града на английски",
    "cart.cityEnglishPlaceholder": "напр. Sofia",
    "cart.cod": "Наложен платеж",
    "cart.completeOrder": "Завърши поръчката",
    "cart.delivery": "Доставка",
    "cart.deliveryAddress": "До адрес",
    "cart.deliveryMethod": "Метод на доставка",
    "cart.deliveryOffice": "До офис",
    "cart.emptyBody": "След като добавите продукти, те ще се появят тук.",
    "cart.emptyTitle": "Количката е празна",
    "cart.enterShippingCity": "Въведете град за доставка.",
    "cart.enterPostcode": "Въведете пощенски код.",
    "cart.enterAddress": "Въведете адрес за доставка.",
    "cart.fullName": "Име и фамилия",
    "cart.home": "Към началото",
    "cart.itemRemove": "Премахни {name} от количката",
    "cart.itemRemoveTitle": "Премахни продукта",
    "cart.loadingShipping": "Изчисляване...",
    "cart.lockedPhone": "Телефонът е заключен към профила. Обновете данните в профила си преди поръчка.",
    "cart.noOffices": "--Няма намерени офиси--",
    "cart.noApms": "--Няма намерени еконтомати--",
    "cart.note": "Бележка",
    "cart.office": "Офис",
    "cart.orderAccepted": "Поръчката е приета",
    "cart.orderDetails": "Данни за поръчка",
    "cart.orderFailed": "Поръчката не беше завършена. Моля, опитайте отново.",
    "cart.orderId": "Номер на поръчка: {orderId}",
    "cart.orderNotCompleted": "Поръчката не е завършена",
    "cart.paymentCancelled": "Плащането е прекъснато",
    "cart.paymentMethod": "Метод на плащане",
    "cart.paymentPlaceholder": "--Изберете метод за плащане--",
    "cart.postcode": "Пощенски код",
    "cart.products": "Продукти",
    "cart.quantityFor": "Количество за {name}",
    "cart.removeCancel": "Отмяна",
    "cart.removeConfirm": "Сигурни ли сте, че искате да премахнете продукта от количката?",
    "cart.selectCityFirst": "--Изберете град, за да се заредят офисите--",
    "cart.selectOffice": "--Изберете офис--",
    "cart.selectApm": "--Изберете еконтомат--",
    "cart.selectOfficeRequired": "Изберете офис за доставка.",
    "cart.selectPaymentRequired": "Изберете метод на плащане.",
    "cart.shippingAtConfirmation": "Ще се изчисли при потвърждение",
    "cart.shippingCalculationFailed": "Неуспешно изчисляване на доставка",
    "cart.submitOrder": "Изпращане...",
    "cart.successBody": "Ще обработим заявката и ще се свържем с вас при нужда от допълнителна информация.",
    "cart.successTitle": "Благодарим за поръчката",
    "cart.tryAgainBody": "Можете да се върнете към количката и да опитате отново.",
    "cart.unitEach": "бр.",
    "cart.unpricedItem": "{name}{variant} няма въведена цена и не може да бъде поръчан.",
    "cart.unavailableItem": "{name} вече не е наличен.",
    "cart.tooManyItem": "Не може да закупите повече от {name}.",
    "cart.tooManyGeneric": "Не може да закупите повече.",
    "customSelect.defaultAria": "Избор",
    "customSelect.empty": "Няма намерени резултати",
    "customSelect.searchAria": "{label} - търсене",
    "customSelect.searchPlaceholder": "Търси...",
    "error.connection": "Няма връзка със сървъра. Моля, опитайте отново след малко.",
    "error.default": "Възникна проблем. Моля, опитайте отново.",
    "form.emailInvalid": "Въведете валиден имейл адрес.",
    "form.emailRequired": "Въведете имейл адрес.",
    "form.nameRequired": "Въведете име.",
    "form.fullNameRequired": "Въведете име и фамилия.",
    "form.passwordConfirmRequired": "Повторете паролата.",
    "form.passwordMin": "Паролата трябва да е поне {min} символа.",
    "form.passwordMismatch": "Паролите не съвпадат.",
    "form.passwordNewRequired": "Въведете нова парола.",
    "form.passwordRequired": "Въведете парола.",
    "form.passwordResetConfirmRequired": "Повторете новата парола.",
    "form.phone": "Телефон",
    "form.checkEmail": "Моля, проверете въведения имейл адрес.",
    "form.checkInput": "Моля, проверете въведените данни.",
    "form.checkReset": "Моля, проверете данните и опитайте отново.",
    "reset.invalidToken": "Линкът за смяна на парола е невалиден или липсва token.",
    "reset.requestSuccess": "Ако има профил с този имейл, ще изпратим линк за смяна на паролата.",
    "reset.success": "Паролата беше сменена успешно. Вече можете да влезете в профила си.",
    "orders.dateTime": "Дата и час",
    "orders.emptyBody": "Когато направите поръчка, тя ще се появи тук.",
    "orders.emptyTitle": "Все още няма поръчки",
    "orders.goCart": "Към количката",
    "orders.goLogin": "Към вход",
    "orders.loginBody": "Трябва да сте вписани, за да видите историята на поръчките си.",
    "orders.loginTitle": "Влезте в профила си",
    "orders.order": "Поръчка",
    "orders.payment": "Плащане",
    "orders.profile": "Профил",
    "orders.subtitle": "Преглед на направените поръчки и техния текущ статус.",
    "orders.title": "Моите поръчки",
    "status.pending": "Очаква обработка",
    "status.processing": "Обработва се",
    "status.completed": "Завършена",
    "status.cancelled": "Отказана",
    "status.paid": "Платена",
    "status.shipped": "Изпратена",
    "common.notSpecified": "Не е посочен",
    "common.scrollTop": "Към началото",
    "validation.phone": "Телефонът трябва да започва с 0 и да е точно 10 цифри.",
  },
  en: {
    "auth.accountExists": "Already have an account?",
    "auth.createAccount": "Create an account",
    "auth.createProfile": "Create profile",
    "auth.email": "Email",
    "auth.forgotKicker": "Profile",
    "auth.forgotLead": "Enter the email for your account and we will send you a link to set a new password.",
    "auth.forgotPassword": "Forgot password",
    "auth.forgotQuestion": "Forgot password?",
    "auth.login": "Sign in",
    "auth.loginFormTitle": "Sign in to your account",
    "auth.loginLead": "Sign in to view orders, delivery details, and customer settings.",
    "auth.loginRetry": "Try again in {seconds} sec.",
    "auth.loginRetryFormal": "Try again in {seconds} sec.",
    "auth.name": "Name",
    "auth.newAccount": "New account",
    "auth.newPassword": "New password",
    "auth.newPasswordLead": "Set a new password for your account. The link is single-use and must be used before it expires.",
    "auth.noAccount": "Don't have an account?",
    "auth.password": "Password",
    "auth.passwordConfirm": "Repeat password",
    "auth.passwordConfirmNew": "Repeat new password",
    "auth.passwordNew": "New password",
    "auth.profile": "Profile",
    "auth.recoverAccess": "Recover access",
    "auth.register": "Register",
    "auth.registering": "Registering...",
    "auth.registerLead": "Create a customer account to order faster and save your basic details for future requests.",
    "auth.rememberMe": "Remember me",
    "auth.resetPassword": "Change password",
    "auth.saveNewPassword": "Save new password",
    "auth.saving": "Saving...",
    "auth.sendLink": "Send link",
    "auth.sending": "Sending...",
    "auth.waitSeconds": "Wait {seconds} sec.",
    "auth.backToLogin": "To sign in",
    "auth.rememberedPassword": "Remembered your password?",
    "auth.accessRestored": "Already have access?",
    "auth.showPassword": "Show password",
    "auth.hidePassword": "Hide password",
    "cart.address": "Delivery address",
    "cart.apm": "Locker",
    "cart.backToCart": "Back to cart",
    "cart.bankTransfer": "Bank transfer",
    "cart.cardPayment": "Card payment",
    "cart.cardPaymentUnavailable": "Card payment is temporarily unavailable.",
    "cart.city": "City",
    "cart.cityEnglishHint": "Enter the city in English",
    "cart.cityEnglishPlaceholder": "e.g. Sofia",
    "cart.cod": "Cash on delivery",
    "cart.completeOrder": "Complete order",
    "cart.delivery": "Delivery",
    "cart.deliveryAddress": "To address",
    "cart.deliveryMethod": "Delivery method",
    "cart.deliveryOffice": "To office",
    "cart.emptyBody": "After you add products, they will appear here.",
    "cart.emptyTitle": "The cart is empty",
    "cart.enterShippingCity": "Enter a delivery city.",
    "cart.enterPostcode": "Enter a postcode.",
    "cart.enterAddress": "Enter a delivery address.",
    "cart.fullName": "Full name",
    "cart.home": "To home",
    "cart.itemRemove": "Remove {name} from cart",
    "cart.itemRemoveTitle": "Remove product",
    "cart.loadingShipping": "Calculating...",
    "cart.lockedPhone": "The phone is locked to your profile. Update your profile details before ordering.",
    "cart.noOffices": "--No offices found--",
    "cart.noApms": "--No lockers found--",
    "cart.note": "Note",
    "cart.office": "Office",
    "cart.orderAccepted": "Order accepted",
    "cart.orderDetails": "Order details",
    "cart.orderFailed": "The order was not completed. Please try again.",
    "cart.orderId": "Order number: {orderId}",
    "cart.orderNotCompleted": "The order is not completed",
    "cart.paymentCancelled": "Payment was cancelled",
    "cart.paymentMethod": "Payment method",
    "cart.paymentPlaceholder": "--Choose payment method--",
    "cart.postcode": "Postcode",
    "cart.products": "Products",
    "cart.quantityFor": "Quantity for {name}",
    "cart.removeCancel": "Cancel",
    "cart.removeConfirm": "Are you sure you want to remove this product from the cart?",
    "cart.selectCityFirst": "--Choose a city to load offices--",
    "cart.selectOffice": "--Choose office--",
    "cart.selectApm": "--Choose locker--",
    "cart.selectOfficeRequired": "Choose a delivery office.",
    "cart.selectPaymentRequired": "Choose a payment method.",
    "cart.shippingAtConfirmation": "Will be calculated on confirmation",
    "cart.shippingCalculationFailed": "Shipping calculation failed",
    "cart.submitOrder": "Sending...",
    "cart.successBody": "We will process the request and contact you if we need more information.",
    "cart.successTitle": "Thank you for your order",
    "cart.tryAgainBody": "You can return to the cart and try again.",
    "cart.unitEach": "pcs.",
    "cart.unpricedItem": "{name}{variant} has no price and cannot be ordered.",
    "cart.unavailableItem": "{name} is no longer available.",
    "cart.tooManyItem": "You cannot purchase more than {name}.",
    "cart.tooManyGeneric": "You cannot purchase more.",
    "customSelect.defaultAria": "Selection",
    "customSelect.empty": "No results found",
    "customSelect.searchAria": "{label} - search",
    "customSelect.searchPlaceholder": "Search...",
    "error.connection": "Cannot connect to the server. Please try again in a moment.",
    "error.default": "Something went wrong. Please try again.",
    "form.emailInvalid": "Enter a valid email address.",
    "form.emailRequired": "Enter an email address.",
    "form.nameRequired": "Enter a name.",
    "form.fullNameRequired": "Enter your full name.",
    "form.passwordConfirmRequired": "Repeat the password.",
    "form.passwordMin": "The password must be at least {min} characters.",
    "form.passwordMismatch": "Passwords do not match.",
    "form.passwordNewRequired": "Enter a new password.",
    "form.passwordRequired": "Enter a password.",
    "form.passwordResetConfirmRequired": "Repeat the new password.",
    "form.phone": "Phone",
    "form.checkEmail": "Please check the entered email address.",
    "form.checkInput": "Please check the entered details.",
    "form.checkReset": "Please check the details and try again.",
    "reset.invalidToken": "The password reset link is invalid or missing a token.",
    "reset.requestSuccess": "If an account exists with this email, we will send a password reset link.",
    "reset.success": "The password was changed successfully. You can now sign in.",
    "orders.dateTime": "Date and time",
    "orders.emptyBody": "When you place an order, it will appear here.",
    "orders.emptyTitle": "There are no orders yet",
    "orders.goCart": "To cart",
    "orders.goLogin": "To sign in",
    "orders.loginBody": "You must be signed in to view your order history.",
    "orders.loginTitle": "Sign in to your account",
    "orders.order": "Order",
    "orders.payment": "Payment",
    "orders.profile": "Profile",
    "orders.subtitle": "Review your placed orders and their current status.",
    "orders.title": "My orders",
    "status.pending": "Pending",
    "status.processing": "Processing",
    "status.completed": "Completed",
    "status.cancelled": "Cancelled",
    "status.paid": "Paid",
    "status.shipped": "Shipped",
    "common.notSpecified": "Not specified",
    "common.scrollTop": "To top",
    "validation.phone": "The phone must start with 0 and be exactly 10 digits.",
  },
  de: {
    "auth.accountExists": "Haben Sie bereits ein Konto?",
    "auth.createAccount": "Konto erstellen",
    "auth.createProfile": "Profil erstellen",
    "auth.email": "E-Mail",
    "auth.forgotKicker": "Profil",
    "auth.forgotLead": "Geben Sie die E-Mail-Adresse Ihres Kontos ein und wir senden Ihnen einen Link zum Festlegen eines neuen Passworts.",
    "auth.forgotPassword": "Passwort vergessen",
    "auth.forgotQuestion": "Passwort vergessen?",
    "auth.login": "Anmelden",
    "auth.loginFormTitle": "Im Konto anmelden",
    "auth.loginLead": "Melden Sie sich an, um Bestellungen, Lieferdaten und Kundeneinstellungen zu sehen.",
    "auth.loginRetry": "Versuchen Sie es in {seconds} Sek. erneut.",
    "auth.loginRetryFormal": "Versuchen Sie es in {seconds} Sek. erneut.",
    "auth.name": "Name",
    "auth.newAccount": "Neues Konto",
    "auth.newPassword": "Neues Passwort",
    "auth.newPasswordLead": "Legen Sie ein neues Passwort für Ihr Konto fest. Der Link kann nur einmal verwendet werden und muss vor Ablauf genutzt werden.",
    "auth.noAccount": "Sie haben kein Konto?",
    "auth.password": "Passwort",
    "auth.passwordConfirm": "Passwort wiederholen",
    "auth.passwordConfirmNew": "Neues Passwort wiederholen",
    "auth.passwordNew": "Neues Passwort",
    "auth.profile": "Profil",
    "auth.recoverAccess": "Zugang wiederherstellen",
    "auth.register": "Registrieren",
    "auth.registering": "Registrierung...",
    "auth.registerLead": "Erstellen Sie ein Kundenkonto, um schneller zu bestellen und Ihre Basisdaten für zukünftige Anfragen zu speichern.",
    "auth.rememberMe": "Angemeldet bleiben",
    "auth.resetPassword": "Passwort ändern",
    "auth.saveNewPassword": "Neues Passwort speichern",
    "auth.saving": "Speichern...",
    "auth.sendLink": "Link senden",
    "auth.sending": "Senden...",
    "auth.waitSeconds": "{seconds} Sek. warten",
    "auth.backToLogin": "Zur Anmeldung",
    "auth.rememberedPassword": "Passwort wieder eingefallen?",
    "auth.accessRestored": "Haben Sie wieder Zugriff?",
    "auth.showPassword": "Passwort anzeigen",
    "auth.hidePassword": "Passwort ausblenden",
    "cart.address": "Lieferadresse",
    "cart.apm": "Paketstation",
    "cart.backToCart": "Zurück zum Warenkorb",
    "cart.bankTransfer": "Banküberweisung",
    "cart.cardPayment": "Kartenzahlung",
    "cart.cardPaymentUnavailable": "Kartenzahlung ist vorübergehend nicht verfügbar.",
    "cart.city": "Stadt",
    "cart.cityEnglishHint": "Bitte Stadt auf Englisch eingeben",
    "cart.cityEnglishPlaceholder": "z. B. Sofia",
    "cart.cod": "Nachnahme",
    "cart.completeOrder": "Bestellung abschließen",
    "cart.delivery": "Lieferung",
    "cart.deliveryAddress": "An Adresse",
    "cart.deliveryMethod": "Versandart",
    "cart.deliveryOffice": "An Econt-Büro",
    "cart.emptyBody": "Nachdem Sie Produkte hinzugefügt haben, erscheinen sie hier.",
    "cart.emptyTitle": "Der Warenkorb ist leer",
    "cart.enterShippingCity": "Geben Sie eine Lieferstadt ein.",
    "cart.enterPostcode": "Geben Sie eine Postleitzahl ein.",
    "cart.enterAddress": "Geben Sie eine Lieferadresse ein.",
    "cart.fullName": "Vor- und Nachname",
    "cart.home": "Zur Startseite",
    "cart.itemRemove": "{name} aus dem Warenkorb entfernen",
    "cart.itemRemoveTitle": "Produkt entfernen",
    "cart.loadingShipping": "Berechnung...",
    "cart.lockedPhone": "Die Telefonnummer ist mit Ihrem Profil verknüpft. Aktualisieren Sie Ihre Profildaten vor der Bestellung.",
    "cart.noOffices": "--Keine Econt-Büros gefunden--",
    "cart.noApms": "--Keine Paketstationen gefunden--",
    "cart.note": "Notiz",
    "cart.office": "Econt-Büro",
    "cart.orderAccepted": "Bestellung angenommen",
    "cart.orderDetails": "Bestelldaten",
    "cart.orderFailed": "Die Bestellung wurde nicht abgeschlossen. Bitte versuchen Sie es erneut.",
    "cart.orderId": "Bestellnummer: {orderId}",
    "cart.orderNotCompleted": "Die Bestellung ist nicht abgeschlossen",
    "cart.paymentCancelled": "Die Zahlung wurde abgebrochen",
    "cart.paymentMethod": "Zahlungsmethode",
    "cart.paymentPlaceholder": "--Zahlungsmethode auswählen--",
    "cart.postcode": "Postleitzahl",
    "cart.products": "Produkte",
    "cart.quantityFor": "Menge für {name}",
    "cart.removeCancel": "Abbrechen",
    "cart.removeConfirm": "Möchten Sie dieses Produkt wirklich aus dem Warenkorb entfernen?",
    "cart.selectCityFirst": "--Stadt auswählen, um Econt-Büros zu laden--",
    "cart.selectOffice": "--Econt-Büro auswählen--",
    "cart.selectApm": "--Paketstation auswählen--",
    "cart.selectOfficeRequired": "Wählen Sie ein Lieferbüro aus.",
    "cart.selectPaymentRequired": "Wählen Sie eine Zahlungsmethode aus.",
    "cart.shippingAtConfirmation": "Wird bei Bestätigung berechnet",
    "cart.shippingCalculationFailed": "Lieferkosten konnten nicht berechnet werden",
    "cart.submitOrder": "Senden...",
    "cart.successBody": "Wir bearbeiten die Anfrage und kontaktieren Sie, falls wir weitere Informationen benötigen.",
    "cart.successTitle": "Vielen Dank für Ihre Bestellung",
    "cart.tryAgainBody": "Sie können zum Warenkorb zurückkehren und es erneut versuchen.",
    "cart.unitEach": "Stk.",
    "cart.unpricedItem": "{name}{variant} hat keinen Preis und kann nicht bestellt werden.",
    "cart.unavailableItem": "{name} ist nicht mehr verfügbar.",
    "cart.tooManyItem": "Sie können nicht mehr als {name} kaufen.",
    "cart.tooManyGeneric": "Sie können nicht mehr kaufen.",
    "customSelect.defaultAria": "Auswahl",
    "customSelect.empty": "Keine Ergebnisse gefunden",
    "customSelect.searchAria": "{label} - Suche",
    "customSelect.searchPlaceholder": "Suchen...",
    "error.connection": "Keine Verbindung zum Server. Bitte versuchen Sie es später erneut.",
    "error.default": "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
    "form.emailInvalid": "Geben Sie eine gültige E-Mail-Adresse ein.",
    "form.emailRequired": "Geben Sie eine E-Mail-Adresse ein.",
    "form.nameRequired": "Geben Sie einen Namen ein.",
    "form.fullNameRequired": "Geben Sie Vor- und Nachnamen ein.",
    "form.passwordConfirmRequired": "Wiederholen Sie das Passwort.",
    "form.passwordMin": "Das Passwort muss mindestens {min} Zeichen lang sein.",
    "form.passwordMismatch": "Die Passwörter stimmen nicht überein.",
    "form.passwordNewRequired": "Geben Sie ein neues Passwort ein.",
    "form.passwordRequired": "Geben Sie ein Passwort ein.",
    "form.passwordResetConfirmRequired": "Wiederholen Sie das neue Passwort.",
    "form.phone": "Telefon",
    "form.checkEmail": "Bitte prüfen Sie die eingegebene E-Mail-Adresse.",
    "form.checkInput": "Bitte prüfen Sie die eingegebenen Daten.",
    "form.checkReset": "Bitte prüfen Sie die Daten und versuchen Sie es erneut.",
    "reset.invalidToken": "Der Link zum Zurücksetzen des Passworts ist ungültig oder enthält keinen Token.",
    "reset.requestSuccess": "Wenn ein Konto mit dieser E-Mail existiert, senden wir einen Link zum Zurücksetzen des Passworts.",
    "reset.success": "Das Passwort wurde erfolgreich geändert. Sie können sich jetzt anmelden.",
    "orders.dateTime": "Datum und Uhrzeit",
    "orders.emptyBody": "Wenn Sie eine Bestellung aufgeben, erscheint sie hier.",
    "orders.emptyTitle": "Es gibt noch keine Bestellungen",
    "orders.goCart": "Zum Warenkorb",
    "orders.goLogin": "Zur Anmeldung",
    "orders.loginBody": "Sie müssen angemeldet sein, um Ihre Bestellhistorie zu sehen.",
    "orders.loginTitle": "Melden Sie sich in Ihrem Konto an",
    "orders.order": "Bestellung",
    "orders.payment": "Zahlung",
    "orders.profile": "Profil",
    "orders.subtitle": "Überblick über Ihre Bestellungen und deren aktuellen Status.",
    "orders.title": "Meine Bestellungen",
    "status.pending": "Wartet auf Bearbeitung",
    "status.processing": "In Bearbeitung",
    "status.completed": "Abgeschlossen",
    "status.cancelled": "Storniert",
    "status.paid": "Bezahlt",
    "status.shipped": "Versendet",
    "common.notSpecified": "Nicht angegeben",
    "common.scrollTop": "Nach oben",
    "validation.phone": "Die Telefonnummer muss mit 0 beginnen und genau 10 Ziffern haben.",
  },
};

Object.entries(EXTRA_TRANSLATIONS).forEach(([language, translations]) => {
  Object.assign(TRANSLATIONS[language], translations);
});

function normalizeLanguage(language) {
  return languageCodes.has(language) ? language : DEFAULT_LANGUAGE;
}

function notifyLanguageChange(language) {
  languageListeners.forEach((listener) => listener());
  window.dispatchEvent(new CustomEvent("language:changed", { detail: { language } }));
}

function subscribeLanguage(listener) {
  languageListeners.add(listener);

  return () => {
    languageListeners.delete(listener);
  };
}

function interpolate(text, values = {}) {
  return text.replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key) => (
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match
  ));
}

export function getStoredLanguage() {
  try {
    return normalizeLanguage(window.localStorage.getItem(LANGUAGE_STORAGE_KEY));
  } catch {
    return DEFAULT_LANGUAGE;
  }
}

export function applyDocumentLanguage(language) {
  document.documentElement.lang = normalizeLanguage(language);
}

export function translate(key, language = getStoredLanguage(), values) {
  const normalizedLanguage = normalizeLanguage(language);
  const text = TRANSLATIONS[normalizedLanguage]?.[key] ?? TRANSLATIONS[DEFAULT_LANGUAGE][key] ?? key;

  return interpolate(text, values);
}

export function useLanguage() {
  const language = useSyncExternalStore(subscribeLanguage, getStoredLanguage, () => DEFAULT_LANGUAGE);
  const t = useCallback((key, values) => translate(key, language, values), [language]);

  return {
    language,
    t,
  };
}

export function storeLanguage(language) {
  const nextLanguage = normalizeLanguage(language);

  try {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
  } catch {
    // The visual switch should still respond if browser storage is unavailable.
  }

  applyDocumentLanguage(nextLanguage);
  notifyLanguageChange(nextLanguage);

  return nextLanguage;
}
